build.target-dir = "./target"

[package]
name = "bricks"
version = "0.1.0"
edition = "2021"
rust-version = "1.92.0"

[workspace]
members = [
    "type_process_builder",
    "process_runner",
]

[dependencies]
type_process_builder = { path = "type_process_builder" }
process_runner = { path = "process_runner" }

#todo https://doc.rust-lang.org/cargo/reference/workspaces.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#https://github.com/slog-rs/example-lib/blob/master/Cargo.toml
#https://github.com/rust-lang/cargo/blob/master/Cargo.toml
